#!/bin/bash

pattern="^source.*\.bigbang$"
sourceline="source \${HOME}/.bigbang"

while IFS= read -r line; do
	[[ ${line} =~ $pattern ]] && continue
	echo "${line}"
done < /dev/stdin

echo "${sourceline}"
