#!/usr/bin/env -S lua -llee

-- GLOBALS
version = "20260215-0"
url = "https://lola.lyderic.com"
cpu = eo("uname -m")

function main()
	if arg[1] then installone(arg[1]) return end
	local output = ea("curl -s %s/cgi-bin/state?cpu=%s", url, cpu)
	local state = json.decode(output)
	for _,i in ipairs(state) do
		printf("\27[1m%-8.8s  \27[m", i.binary..":")
		local c = get_situation(i.binary)
		if not c then goto next end
		if c.parent ~= "/usr/local/bin/" then
			printf("\27[90mskipped as found in %q\27[m\n", c.parent)
			goto next
		end
		if c.cksum == i.cksum and c.size == i.size then
			printf("\27[90mup to date (sum=%s, size=%s)\27[m\n",
			c.cksum, c.size)
		else
			print("\27[32mupdate available\27[m")
			deploy(i.binary)
		end
	::next::end
end

-- get situation of a binary on the host, i.e.path, parent, cksum
-- and size
-- if a binary is not found, it is deployed
function get_situation(binary)
	local t = {} -- local situation on host
	t.binary = binary
	t.path = eo("command -v %q", binary)
	if not t.path then
		printf("\27[33m%s: binary not found\27[m\n", binary)
		deploy(binary)
		return nil
	end
	t.parent = t.path:match(".*/")
	t.cksum, t.size = eo("cksum %q",t.path):match("(%d+) (%d+)")
	return t
end

-- if binary not installable with pacman, then get binary from lola
-- and put it in /usr/local/bin
-- if binary already found in /usr/local/bin, it is overwritten
function deploy(binary)
	printf("\27[7m %s \27[m", binary)
	if pacman(binary) then return end
	local buf = "/dev/shm/"..binary..".gz"
	local curl_cmd = f("curl -sLo %q -w '%%%%{json}' %s/binaries/%s/%s",
		buf, url, cpu, binary..".gz")
	print("---> [XeQ] " .. curl_cmd)
	local result = json.decode(ea(curl_cmd))
	local rcode = result.http_code
	if rcode == 200 then
		printf("\27[32mOK\27[m CODE %d\n",rcode)
	else
		printf("\27[31mERROR, HTTP response: %d\27[m\n", rcode)
		if abs(buf) then io.write(io.open(buf):read("a")) end
		return
	end
	local dst="/usr/local/bin/"..binary
	if not x("zcat %q | sudo tee %q >/dev/null",buf,dst) then return end
	if not x("sudo chown -v 0:0 %q",dst) then return end
	if not x("sudo chmod -v 0755 %q",dst) then return end
	os.remove(buf)
end

-- try to install binary with pacman
function pacman(binary)
	if not x("[ -x /usr/bin/pacman ]") then return false end
	print("---> trying pacman...")
	return x("sudo pacman --color=never -S --needed %s",binary)
end

-- use this to install a single, optional, binary
-- or to force the reinstall of a installed binary
function installone(binary)
	deploy(binary)
end

main()
