#!/usr/bin/env -S lua -llee

local version = "20260509-1"
local progname = "lod"
local defaultwidth = 58
local dbg = env("debug") or false

function main()
	local argparse = require("argparse")
	local parser = argparse() {
		name = progname,
		description = "\27[1mlowdown command line viewer\27[m",
	}
	parser:argument("file", "A markdown file")
	parser:option("-w") {
		argname = "width",
		convert = tonumber,
		description = f("Word wrap (default=%d)", defaultwidth), 
		default = defaultwidth,
	}
	parser:flag("-n") {
		description = "Don't use pager",
		default = false,
	}
	parser:flag("--version") {
		description = "show version",
		default = false,
		action = function()
			print(version)
			os.exit(0)
		end
	}
	local a = parser:parse()
	if dbg then print(">>>>args: "..json.encode(a)) end
	local file, width = a.file, a.w
	local cols = tonumber(eo("tput cols")) or 100
	if dbg then printf(">>>>cols = %d\n", cols) end
	if width > cols then width = cols end
	if width == 0 or cols < defaultwidth then
		width = cols - 2
	end
	local pager = true
	if a.n then pager = false end
	local cmd = getcmd(width, file, pager)
	if dbg then print(">>>>[XeQ] "..cmd) end
	x(cmd)
end

function getcmd(width, file, pager)
local ppipe = pager and " | less -FRIX" or ""
return f([[lowdown -tterm \
--out-no-smart \
--term-columns=%d \
--term-width=%d \
--term-hpadding=2 \
--term-vmargin=1 %q \
%s]], width, width, file, ppipe)
end

main()
