#!/usr/bin/env -S lua -llee

-- globals
version = "20260728-3"
wgdump = {} -- output of wg-json
peerNames = {} -- mapping pubkey-peername
display = env("WG_STATUS_DISPLAY") or "full"

function main()
	checkroot() -- cannot run wg-json if not root
	wgdump = json.decode(ea("wg-json")) -- global
	peerNames = loadPeerNames() -- global
	local ifaces = {}
	if #arg == 0 then
		for iface in pairs(wgdump) do append(ifaces, iface) end
	else
		for iface in pairs(wgdump) do
			if iface == arg[1] then append(ifaces, iface) end
		end
	end
	table.sort(ifaces)
	processInterfaces(ifaces)
end

function processInterfaces(ifaces)
	for _,name in ipairs(ifaces) do
		printf("\27[1;4m%-64.64s\27[m\n", name)
		local pubkeys = {}
		for pubkey in pairs(wgdump[name].peers) do
			append(pubkeys, pubkey)
		end
		table.sort(pubkeys)
		for _,pubkey in ipairs(pubkeys) do
			if display == "full" then
				fulldisplay(name, pubkey)
			else
				summary(name, pubkey)
			end
		end
	end
end

function summary(name, pubkey)
	local d = wgdump[name].peers[pubkey]
	printf("\27[1;97m%-8.8s\27[m ", getNameFromPubkey(pubkey))
	if d.allowedIps then
		printf("%16.16s", concat(d.allowedIps," "))
	end
	if d.transferTx then
		printf("%12.12s", "TX="..bfmt(d.transferTx))
	end
	if d.transferRx then
		printf("%12.12s", "RX="..bfmt(d.transferRx))
	end
	if d.latestHandshake then
		last = os.date("%Y-%m-%d %H:%M:%S", d.latestHandshake)
		diff = os.difftime(os.time(), d.latestHandshake)
		printf("   \27[97m%s\27[m\n", dhms(diff))
	end
end

function fulldisplay(name, pubkey)
	local d = wgdump[name].peers[pubkey]
	printf("\27[4mpeer\27[m: ")
	printf("\27[1;97m%s\27[m ", getNameFromPubkey(pubkey))
	printf("\27[3m%s\27[m\n", pubkey)
	printf(" • Endpoint: %s ", d.endpoint)
	local keepalive = d.persistentKeepalive or 0
	if keepalive > 0 then
		printf("(keepalive=%ds)", keepalive)
	end
	print()
	if d.allowedIps then
		printf(" • Allowed IPs: %s\n", concat(d.allowedIps," "))
	end
	if d.transferTx and d.transferRx then
		printf(" • Transfers: TX=%s RX=%s\n",
			bfmt(d.transferTx), bfmt(d.transferRx))
	end
	if d.latestHandshake then
		last = os.date("%Y-%m-%d %H:%M:%S", d.latestHandshake)
		diff = os.difftime(os.time(), d.latestHandshake)
		printf(" • Latest Handshake: ")
		printf("%s (\27[97m%s ago\27[m)\n", last, dhms(diff))
	end
end

function loadPeerNames()
	local peerPath = "/etc/wireguard/peers.csv"
	if not abs(peerPath) then return end
	return load(ea("yq -pcsv -olua %q", peerPath))()
end

function getNameFromPubkey(pubkey)
	if not peerNames then return "--unset--" end
	for _,peer in ipairs(peerNames) do
		if peer.pubkey == pubkey then
			return peer.name
		end
	end
	return "--unset--"
end

function checkroot()
	local uid = tonumber(eo("id -u"))
	if uid ~= 0 then
		printf("UID=%d\nyou're not root!\n", uid)
		os.exit(22)
	end
end

main()
