#!/usr/bin/env -S lua -llee

-- globals
version = "20260825-1"
wgdump = {} -- output of wg-json
peerNames = {} -- mapping pubkey-peername
cache = "/dev/shm/peers.lua"

function main()
	checkroot() -- cannot run wg-json if not root
	wgdump = json.decode(ea("wg-json")) -- global
	peerNames = loadPeerNames() -- global
	local ifaces = {} -- we do this to sort
	if #arg == 0 then
		for iface in pairs(wgdump) do append(ifaces, iface) end
	else
		for iface in pairs(wgdump) do
			if iface == arg[1] then append(ifaces, iface) end
		end
	end
	table.sort(ifaces)
	processInterfaces(ifaces)
end

-- ifacename: wireguard interface names (wgXX)
-- peerspubkeys: peers pubkeys
function processInterfaces(ifaces)
	for _,ifacename in ipairs(ifaces) do
		local lines = {}
		append(lines, headerLine(ifacename))
		local peers = {}
		for pubkey,d in pairs(wgdump[ifacename].peers) do
			local peer = {}
			peer.id = pubkey:sub(1,4)
			peer.name = getNameFromPubkey(pubkey)
			peer.endpoint = d.endpoint
			peer.ips = d.allowedIps
			peer.tx = d.transferTx or 0
			peer.rx = d.transferRx or 0
			peer.keepalive = d.persistentKeepalive
			peer.last = d.latestHandshake or 0
			if peer.last then
				peer.diff = os.difftime(os.time(), peer.last) or 0
			end
			peer.ago = dhms(peer.diff)
			peer.color = "\27[32m" -- green by default
			if peer.last == 0 then
				peer.color = "\27[2m"
				peer.ago = "never"
			elseif peer.diff > 180 then -- 3 minutes
				peer.color = "\27[34m"
			end
			append(peers, peer)
		end
		table.sort(peers, function(a, b)
			return a.last > b.last
		end)
		local inactives = {}
		for _, peer in ipairs(peers) do
			if peer.last > 0 then
				append(lines, peerLine(peer))
			else
				append(inactives, peer.name)
			end
		end
		display(lines)
		if #inactives > 0 then
			table.sort(inactives)
			printf("\27[2;3mInactives: %s\27[m\n",
				concat(inactives, " "))
		end
		print()
	end
end

function display(lines)
	local column = e("column -t", "w")
	for _, line in ipairs(lines) do
		column:write(line.."\n")
	end
	column:close()
end

function headerLine(ifacename)
	return "\27[1;4m"..ifacename
	.." Id IP TX RX Last \27[m"
end

function peerLine(d)
	local line = {}
	append(line, d.color..d.name)
	append(line, d.id)
	if d.ips then
		local ip = d.ips[1]
		if #d.ips > 1 then ip = ip .. "+" end
		append(line, ip)
	end
	append(line, bfmt(d.tx))
	append(line, bfmt(d.rx))
	append(line, d.ago.."\27[m")
	return concat(line, " ")
end

function fetch()
	local path = "/etc/wireguard/peers.csv"
	local fh = io.open(path)
	local yq = "yq -pcsv -olua --lua-unquoted"
	if not fh then -- if no peers.csv, fetch it from lola
		local url = "https://lola.lyderic.com/peers.csv"
		local creds = "runlola:tusojos"
		x("curl -u %s -sL %q | %s > %q", creds, url, yq, cache)
	else
		fh:close()
		print("found " .. path)
		x("%s %q > %q", yq, path, cache)
	end
	print("\27[3mpeers cached\27[m")
end

function loadPeerNames()
	local fh = io.open(cache)
	if not fh then fetch() else fh:close() end
	return loadfile(cache)()
end

function getNameFromPubkey(pubkey)
	if not peerNames then return "???" end
	for _,peer in ipairs(peerNames) do
		if peer.pubkey == pubkey then
			return peer.name
		end
	end
	return "???"
end

function checkroot()
	local uid = tonumber(eo("id -u"))
	if uid ~= 0 then
		printf("UID=%d\nyou're not root!\n", uid)
		os.exit(22)
	end
end

main()
